"""celery_task_executions

Revision ID: 10f1f6bba4c9
Revises: 7f15db6e3527
Create Date: 2026-09-12 15:09:04.167126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10f1f6bba4c9'
down_revision: Union[str, None] = '7f15db6e3527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('collection_384_554114_keywords_idx', table_name='collection_384_554114', postgresql_using='gin')
    op.drop_table('collection_384_554114')
    op.drop_index('collection_384_58522_keywords_idx', table_name='collection_384_58522', postgresql_using='gin')
    op.drop_table('collection_384_58522')
    op.drop_index('collection_384_85210_keywords_idx', table_name='collection_384_85210', postgresql_using='gin')
    op.drop_table('collection_384_85210')
    op.drop_index('collection_384_8857621_keywords_idx', table_name='collection_384_8857621', postgresql_using='gin')
    op.drop_index('collection_384_8857621_vector_idx', table_name='collection_384_8857621', postgresql_using='hnsw')
    op.drop_table('collection_384_8857621')
    op.create_index('ix_chunk_metadata_keywords', 'datachunks', [sa.text("(chunk_metadata -> 'keywords')")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_metadata_keywords', table_name='datachunks', postgresql_using='gin')
    op.create_table('collection_384_8857621',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['datachunks.chunk_id'], name='collection_384_8857621_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_8857621_pkey')
    )
    op.create_index('collection_384_8857621_vector_idx', 'collection_384_8857621', ['vector'], unique=False, postgresql_using='hnsw')
    op.create_index('collection_384_8857621_keywords_idx', 'collection_384_8857621', [sa.text("(metadata -> 'keywords'::text)")], unique=False, postgresql_using='gin')
    op.create_table('collection_384_85210',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['datachunks.chunk_id'], name='collection_384_85210_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_85210_pkey')
    )
    op.create_index('collection_384_85210_keywords_idx', 'collection_384_85210', [sa.text("(metadata -> 'keywords'::text)")], unique=False, postgresql_using='gin')
    op.create_table('collection_384_58522',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['datachunks.chunk_id'], name='collection_384_58522_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_58522_pkey')
    )
    op.create_index('collection_384_58522_keywords_idx', 'collection_384_58522', [sa.text("(metadata -> 'keywords'::text)")], unique=False, postgresql_using='gin')
    op.create_table('collection_384_554114',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['datachunks.chunk_id'], name='collection_384_554114_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_554114_pkey')
    )
    op.create_index('collection_384_554114_keywords_idx', 'collection_384_554114', [sa.text("(metadata -> 'keywords'::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
