pgvector:
    image: pgvector/pgvector:0.8.6-pg18-trixie
    container_name: pgvector
    ports:
      - "5400:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql   # changed from /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_MAIN_DATABASE}   # add this too, see below
    networks:
      - backend
    restart: always



networks:
  backend:

volumes:
  pgvector_data:
    
